### ISSUE TITLE
Cannot integrate with jsdom

### ISSUE THREAD

**Issue by batusai513** [CodingZeal/react-boilerplate#50]
when i try to add jsdom and the basic boilerplate to make it work
specHelper.js
```js
global.document = require('jsdom').jsdom('<body><div id="root"></div></body>');
global.window = document.defaultView;
global.navigator = window.navigator;
```
and i run npm test it trows some errors 
```bash
WARNING in ./~/jsdom/lib/jsdom/utils.js
Module not found: Error: Cannot resolve module 'canvas' in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom
resolve module canvas in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom
  looking for modules in /Users/wardrakus/projects/react-boilerplate/client
    /Users/wardrakus/projects/react-boilerplate/client/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/react-boilerplate/client
      resolve file
        /Users/wardrakus/projects/react-boilerplate/client/canvas doesn't exist
        /Users/wardrakus/projects/react-boilerplate/client/canvas.js doesn't exist
  looking for modules in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules
    /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules
      resolve file
        /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas doesn't exist
        /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas.js doesn't exist
  looking for modules in /Users/wardrakus/projects/react-boilerplate/node_modules
    /Users/wardrakus/projects/react-boilerplate/node_modules/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/react-boilerplate/node_modules
      resolve file
        /Users/wardrakus/projects/react-boilerplate/node_modules/canvas doesn't exist
        /Users/wardrakus/projects/react-boilerplate/node_modules/canvas.js doesn't exist
  looking for modules in /Users/wardrakus/projects/node_modules
    /Users/wardrakus/projects/node_modules/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/node_modules
      resolve file
        /Users/wardrakus/projects/node_modules/canvas doesn't exist
        /Users/wardrakus/projects/node_modules/canvas.js doesn't exist
[/Users/wardrakus/projects/react-boilerplate/client/canvas]
[/Users/wardrakus/projects/react-boilerplate/client/canvas]
[/Users/wardrakus/projects/react-boilerplate/client/canvas.js]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas.js]
[/Users/wardrakus/projects/react-boilerplate/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/canvas.js]
[/Users/wardrakus/projects/node_modules/canvas]
[/Users/wardrakus/projects/node_modules/canvas]
[/Users/wardrakus/projects/node_modules/canvas.js]
 @ ./~/jsdom/lib/jsdom/utils.js 343:19-36

WARNING in ./~/jsdom/lib/jsdom/living/xmlhttprequest.js
Critical dependencies:
19:23-30 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/jsdom/lib/jsdom/living/xmlhttprequest.js 19:23-30
WARNING in ./~/jsdom/lib/jsdom/living/window/History.idl                                                                                                              [12/1355]
Module parse failed: /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/window/History.idl The keyword 'enum' is reserved (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: The keyword 'enum' is reserved (1:0)
    at Parser.pp.raise (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:918:13)
    at Parser.pp.parseIdent (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:669:203)
    at Parser.pp.parseExprAtom (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:283:21)
    at Parser.pp.parseExprSubscripts (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOps (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseStatement (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:1750:23)
    at Parser.pp.parseTopLevel (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:1645:21)
    at Parser.parse (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:1613:17)
    at Object.parse (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:880:44)
    at Parser.parse (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/wardrakus/projects/react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/wardrakus/projects/react-boilerplate/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/wardrakus/projects/react-boilerplate/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ./~/jsdom/lib/jsdom/living ^\.\/.*$
ERROR in ./~/jsdom/lib/jsdom/living/generated/DOMPointReadOnly.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../nodes/DOMPointReadOnly-impl.js in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated
resolve file
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js doesn't exist
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js.js doesn't exist
resolve directory
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js doesn't exist (directory default file)
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js/package.json doesn't exist (directory description file)
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js.js]
 @ ./~/jsdom/lib/jsdom/living/generated/DOMPointReadOnly.js 135:13-57

ERROR in ./~/jsdom/lib/jsdom/living/generated/ScrollIntoViewOptions.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./ScrollOptions in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated
resolve file
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions doesn't exist
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions.js doesn't exist
resolve directory
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions doesn't exist (directory default file)
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions/package.json doesn't exist (directory description file)
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions.js]
 @ ./~/jsdom/lib/jsdom/living/generated/ScrollIntoViewOptions.js 6:22-48
```
how do you run tests that needs the actual DOM?, it is posible to add jsdom to this setup?

thanks

**Comment by randycoulman** [comment]
We haven't tried using jsdom yet with our setup.  We typically test our components using shallow rendering rather than with an actual DOM.

From the error messages, it looks like webpack is having trouble processing jsdom.  Here some ideas of things you can try:

* Install the [canvas](https://www.npmjs.com/package/canvas) package.  jsdom's docs suggest that it will recognize it if it is present.
* Find a webpack loader to handle the `*.idl` files that it is complaining about.  I'm not sure if such a thing exists.
* Search for other people's advice on using jsdom with webpack.  That's usually what I have to do when I encounter strange webpack issues with a new package.

I'll keep the issue open for a bit to see if anyone else has better ideas.

**Comment by joefraley** [comment]
You need to add native node libraries as externals (for some reason...):

```javascript
const nodeExternals = require('webpack-node-externals')
const testConfig = Object.assign({}, baseConfig, {
    target: 'node',
    externals: [nodeExternals()] // this is the thing missing that crashes `npm test`
})
```

This is alluded to very sideways in the mocha-webpack docs: https://www.npmjs.com/package/mocha-webpack, search for "nodeExternals"

**Comment by randycoulman** [comment]
@joefraley Thanks for the suggestion.  We were using webpack-node-externals at one point and found that it conflicts with a lint rule in eslint-plugin-import.  See #43 for some discussion on this.  That said, if it resolves the issue with jsdom, maybe it's worth making that tradeoff.

**Comment by randycoulman** [comment]
@batusai513 We've now switched over to Karma as the test runner.  I expect that will resolve the issue here.  If not, please re-open.  Thanks!
